### ISSUE TITLE
tips?

### ISSUE THREAD

**Issue by EdSaleh** [kdn251/interviews#101]
Can you provide general interview tips?
Example: https://github.com/yangshun/tech-interview-handbook/blob/master/preparing/cheatsheet.md

And

https://github.com/yangshun/tech-interview-handbook/blob/master/preparing/README.md

**Comment by kdn251** [comment]
I'd be happy to do that, great idea! I've also been considering making a video like that on my YouTube channel. I also walk through solutions and explain my approach in my videos there if you're interested in checking it out: https://www.youtube.com/channel/UCKvwPt6BifPP54yzH99ff1g
