### ISSUE TITLE
links to the ACM

### ISSUE THREAD

**Issue by omouse** [kdn251/interviews#11]
The Association of Computing Machinery (ACM) has a ton of computer science news and journals and conference papers.

The Communications of the ACM is a great resource, along with ACM Queue. Could you link to those?

* http://cacm.acm.org/ - Communications of the ACM
* http://queue.acm.org/ - ACM queue
* http://technews.acm.org/ - tech news

They've also got a nice list of webinars happening: https://learning.acm.org/webinar/index.cfm

**Comment by kdn251** [comment]
These look great, thank you so much for these links!
