### ISSUE TITLE
Could I translate this document into Chinese and share with more Chinese developers?

### ISSUE THREAD

**Issue by sqrthree** [kdn251/interviews#12]
We have an organization of translation technology articles, and We have translated a lot of documents like [jwasham/coding-interview-university](https://github.com/jwasham/coding-interview-university/blob/master/translations/README-cn.md). Could we translate this document into Chinese and share with more Chinese developers? We will open a PR once it's done.  ❤️ 

About our organization: [xitu/gold-miner](https://github.com/xitu/gold-miner)

**Comment by zxp0505** [comment]
give you a star

**Comment by kdn251** [comment]
Absolutely, the more people this can help, the better! Please open a PR when it's finished.
