### ISSUE TITLE
SearchInRotatedSortedArray Invalid Solution

### ISSUE THREAD

**Issue by nitesh619** [kdn251/interviews#122]
Doen's work for below Input:
[1,1,3,1]
3

Expected: 2
Actual: -1

**Comment by joimxjtuse** [comment]
i think you have not realize the premise：
“an array sorted in ascending order”.

**Comment by Walshf0411** [comment]
It is said in the first line of the code that, yoy may assume no duplicates occur in the array. So i guess the code does not work for duplicates.

**Comment by joimxjtuse** [comment]
your arr should be : [1, 1, 1, 3],   while you search "1", it may not the right position what you want.

**Comment by nitesh619** [comment]
You are right, no duplicates are allowed :)
