### ISSUE TITLE
How did you guys visualize all those algorithms?

### ISSUE THREAD

**Issue by rohitkrishna094** [kdn251/interviews#123]
Which software did you use I mean? Or were they just copied from wikipedia and other places online? Thanks

**Comment by viragumathe5** [comment]
It is not about visualizing the algorithms it is about to understand them just seek for a solution and think before you write something 
Initially, you don't look for its complexity just implement it as worst as you can and then make it efficient

**Comment by rohitkrishna094** [comment]
@viragumathe5 I totally understand what you are saying. But I just wanted to know how these visualizations were done. I was planning on creating a new project where I could visualize all sorting algorithms for example, like this video. 

https://www.youtube.com/watch?v=kPRA0W1kECg

Visualization would be a nice way to practice such algorithms since you can learn as well as see them with colors and graphs and such. :)

**Comment by viragumathe5** [comment]
Yeah it's nice to visualize algorithms it helps us to understand very well 

so according to me, you can visualize these algorithms using Computational Geometry, it is like you are drawing things on a graph paper
for this video 
You can take n numbers of lines with different heights and just apply the sorting algorithms you like and you can able to see the magic of algorithms then 

Using CG you can visualize different algorithms as well 


Now an important thing how to apply it 

there are two well-known libs for it
1. LEDA (Library of Efficient Data-types and Algorithms) 
2. CGAL (The Computational Geometry Algorithms Library)
    https://www.cgal.org/

LEDA is not free it comes with enterprise edition 
you can use CGAL its a good lib for CG

also if you want a book to read on CG go through the following 

[Computational Gemoetry.pdf](https://github.com/kdn251/interviews/files/3269322/Computational.Gemoetry.pdf)


this is CGAL tutorials you can go through it
 https://doc.cgal.org/latest/Manual/tutorials.html
