### ISSUE TITLE
Should be min of min and value at indes

### ISSUE THREAD

**Issue by kedhas** [kdn251/interviews#217]
https://github.com/kdn251/interviews/blob/a70c2250ec5f2e43972a359e050182f970ea2ffd/leetcode/array/BestTimeToBuyAndSellStock.java#L30

should be 
min = Math.min(min, prices[i])

**Comment by Jiruiyang** [comment]
来信收到，谢谢，祝您一切顺利！

**Comment by kedhas** [comment]
False positive
