### ISSUE TITLE
Adding a direct link to code in directory tree in readme.md

### ISSUE THREAD

**Issue by jsroyal** [kdn251/interviews#35]
I have been past couple time and seen the directory tree of code implementation.
So it would be good to add a relative link to the direct code.

**Comment by EugenHotaj** [comment]
Not sure what you mean exactly. Could you expand on what you mean?

**Comment by jsroyal** [comment]
@EugenHotaj 
I'm talking about the last part of readme.md file.
Where a very well structure directory of code implementation.
![image](https://cloud.githubusercontent.com/assets/10773353/25115125/7ccc0588-2421-11e7-9698-e5c075ed6c04.png)
So what I'm saying is that why not give direct link the code in repo directory.
I think now you get it of relative link of code in readme file.

**Comment by EugenHotaj** [comment]
Yea that's a good point. If @kdn251 is good with that I'd be happy to approve any PRs you send my way.

**Comment by jsroyal** [comment]
@kdn251 Are you agree with that? It would be good to direct link so please give me approved to work this PRs

**Comment by jsroyal** [comment]
@kdn251 Are you agree about my suggestion feature?
Please have look and approved to work on that.

**Comment by kdn251** [comment]
That'd be great @jsroyal. Great idea!

**Comment by jsroyal** [comment]
As of now, I think this issue is fixed.Need to review of PR #38 
So I want to close this issue.
What do you guys @EugenHotaj @kdn251 think about it?
